sonar.projectKey=Upasana-1204_InfraWatch
sonar.organization=upasana-1204
sonar.projectName=InfraWatch
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/*.json,**/.git/**,**/node_modules/**
